# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Build app
        working-directory: ./quasar-project  
        run: |
          npm install
          ./node_modules/.bin/quasar build

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: build-app-artifact
          path: ./quasar-project/dist/spa
          retention-days: 5    
      

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: build-app-artifact
      - name: Create AuthFile
        run: |
          echo '${{ secrets.GCP_CREDS }}' > ./gcp_auth.json
      - name: Auth to GCP
        run: |
          gcloud auth activate-service-account --key-file="./gcp_auth.json"
          rm -rf ./gcp_auth.json
      - name: Deploy to production GCP
        if: github.ref == 'refs/heads/main'
        run: |
          gsutil -m rsync -dr ./ gs://storydata-figagency-com
      - name: Deploy to develop GCP
        if: github.ref == 'refs/heads/develop'
        run: |
          gsutil -m rsync -dr ./ gs://dev-storydata-figagency-com      
