# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v1
      - name: Build app
        working-directory: ./quasar-project  
        run: |
          npm install
          ./node_modules/.bin/quasar build
      - name: Create AuthFile
        working-directory: ./quasar-project/ 
        run: |
          echo '${{ secrets.GCP_CREDS }}' > ./gcp_auth.json
      - name: Auth to GCP
        working-directory: ./quasar-project/
        run: |
          gcloud auth activate-service-account --key-file="./gcp_auth.json"
      - name: Deploy to production GCP
        working-directory: ./quasar-project/dist/spa 
        if: github.ref == 'refs/heads/main'
        run: |
          gsutil -m rsync -dr ./ gs://storydata-figagency-com
      - name: Deploy to develop GCP
        working-directory: ./quasar-project/dist/spa     
        if: github.ref == 'refs/heads/develop'
        run: |
          gsutil -m rsync -dr ./ gs://dev-storydata-figagency-com      
